insert into team_members (id, initials, name, role, bio, email, number, avatar_url, sort_order, is_active) values
('abdelgader-idris','AI','ABDELGADER IDRIS','Web Developer','Builds and maintains reliable web features that support daily business operations.','abdelgader.idris@synergypm.com','32',null,32,true),
('afsal-mohamed','AM','Afsal Mohamed','Head of Operation UK','Leads UK operations, improving delivery standards and cross-team coordination.','afsal.mohamed@synergypm.com','33',null,33,true),
('ahsan-abbasi','AA','Ahsan Abbasi','Graphic Designer','Creates brand-aligned visual assets for campaigns, digital content, and marketing.','ahsan.abbasi@synergypm.com','34',null,34,true),
('alexis-macaraeg','AM','Alexis Macaraeg','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','alexis.macaraeg@synergypm.com','35',null,35,true),
('anwarsha-ebrahimkutty','AE','Anwarsha Ebrahimkutty','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','anwarsha.ebrahimkutty@synergypm.com','36',null,36,true),
('arsha-rahulan-sajitha','AR','Arsha Rahulan Sajitha','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','arsha.rahulan.sajitha@synergypm.com','37',null,37,true),
('arunima-viswam','AV','Arunima Viswam','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','arunima.viswam@synergypm.com','38',null,38,true),
('athul-chandran','AC','Athul Chandran','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','athul.chandran@synergypm.com','39',null,39,true),
('chitra-menon','CM','Chitra Menon','Personal Assistant','Supports leadership with scheduling, communication flow, and daily priorities.','chitra.menon@synergypm.com','40',null,40,true),
('christopher-oliver','CO','Christopher Oliver','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','christopher.oliver@synergypm.com','41',null,41,true),
('delvin-davis','DD','Delvin Davis','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','delvin.davis@synergypm.com','42',null,42,true),
('ervin-lingon','EL','Ervin Lingon','Motion Graphic Designer','Produces engaging motion visuals for campaigns, media assets, and brand storytelling.','ervin.lingon@synergypm.com','43',null,43,true),
('gladson-noronha','GN','Gladson Noronha','Head of Operations','Leads operational strategy, process quality, and performance across teams.','gladson.noronha@synergypm.com','44',null,44,true),
('gokul-gopakumar','GG','Gokul Gopakumar','Head of Operations','Leads operational strategy, process quality, and performance across teams.','gokul.gopakumar@synergypm.com','45',null,45,true),
('haja-sarbudeen','HS','Haja Sarbudeen','Web Developer','Builds and maintains reliable web features that support daily business operations.','haja.sarbudeen@synergypm.com','46',null,46,true),
('irshad-salih','IS','Irshad Salih','Audit Accountant','Supports audits, validates controls, and ensures reliable financial compliance records.','irshad.salih@synergypm.com','47',null,47,true),
('jibeesh-jacob','JJ','Jibeesh Jacob','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','jibeesh.jacob@synergypm.com','48',null,48,true),
('joanna-reyes','JR','Joanna Reyes','Administrative Assistant','Supports office administration, document flow, and day-to-day team coordination.','joanna.reyes@synergypm.com','49',null,49,true),
('joyel-jose','JJ','Joyel Jose','Odoo Developer','Develops and optimizes Odoo modules to improve workflows and system reliability.','joyel.jose@synergypm.com','50',null,50,true),
('kimenthri-govender','KG','Kimenthri Govender','Sales Admin Assistant','Supports sales administration, pipeline updates, and follow-up coordination tasks.','kimenthri.govender@synergypm.com','51',null,51,true),
('krishna-devi','KD','Krishna Devi','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','krishna.devi@synergypm.com','52',null,52,true),
('manshaf-siddiqui','MS','Manshaf Siddiqui','Web Developer','Builds and maintains reliable web features that support daily business operations.','manshaf.siddiqui@synergypm.com','53',null,53,true),
('mohamed-ali-jinna','MA','Mohamed Ali Jinna','Accounts Assistant','Assists with daily accounting tasks, reconciliations, and finance documentation flow.','mohamed.ali.jinna@synergypm.com','54',null,54,true),
('mohammed-arfan','MA','Mohammed Arfan','Forensics Accountant','Analyzes financial evidence, supports investigations, and strengthens control reviews.','mohammed.arfan@synergypm.com','55',null,55,true),
('mohammed-hussain-suleman','MH','Mohammed Hussain Suleman','Logistics','Coordinates logistics activities to ensure timely movement and delivery operations.','mohammed.hussain.suleman@synergypm.com','56',null,56,true),
('mohammed-shamis','MS','Mohammed Shamis','Data Analyst','Transforms data into clear insights that support planning and business decisions.','mohammed.shamis@synergypm.com','57',null,57,true),
('morati-moloto','MM','Morati Moloto','Media Specialist','Manages media assets and delivery quality across digital and campaign channels.','morati.moloto@synergypm.com','58',null,58,true),
('muhammed-hisham','MH','Muhammed Hisham','Motion Graphic Designer','Produces engaging motion visuals for campaigns, media assets, and brand storytelling.','muhammed.hisham@synergypm.com','59',null,59,true),
('muhammed-muzammil','MM','Muhammed Muzammil','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','muhammed.muzammil@synergypm.com','60',null,60,true),
('muhammed-razi','MR','Muhammed Razi','Senior Accountant','Leads accounting accuracy, reporting reviews, and financial control improvements.','muhammed.razi@synergypm.com','61',null,61,true),
('nilesh-thanki','NT','Nilesh Thanki','Finance Manager','Leads financial planning, reporting, and controls to support strategic growth.','nilesh.thanki@synergypm.com','62',null,62,true),
('nisamudeen-nasar','NN','Nisamudeen Nasar','3D Visualizer','Creates high-quality 3D visuals that support presentations and creative production.','nisamudeen.nasar@synergypm.com','63',null,63,true),
('pauline-potato','PP','Pauline Potato','Administrative Assistant','Supports office administration, document flow, and day-to-day team coordination.','pauline.potato@synergypm.com','64',null,64,true),
('quenie-rose','QR','Quenie Rose','Personal Assistant to CEO','Supports the CEO with scheduling, priorities, and efficient executive coordination.','quenie.rose@synergypm.com','65',null,65,true),
('rahul-raghunath','RR','Rahul Raghunath','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','rahul.raghunath@synergypm.com','66',null,66,true),
('rahul-ramanarayanan','RR','Rahul Ramanarayanan','Graphic Designer','Creates brand-aligned visual assets for campaigns, digital content, and marketing.','rahul.ramanarayanan@synergypm.com','67',null,67,true),
('randeev-harikumar','RH','Randeev Harikumar','3D Visualizer','Creates high-quality 3D visuals that support presentations and creative production.','randeev.harikumar@synergypm.com','68',null,68,true),
('riddhi-ghelani','RG','Riddhi Ghelani','Social Media Executive','Executes social media plans, content publishing, and engagement tracking activities.','riddhi.ghelani@synergypm.com','69',null,69,true),
('sabith-manegar','SM','Sabith Manegar','Data Analyst','Transforms data into clear insights that support planning and business decisions.','sabith.manegar@synergypm.com','70',null,70,true),
('sarathlal-raveendran','SR','Sarathlal Raveendran','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','sarathlal.raveendran@synergypm.com','71',null,71,true),
('shahabas-puthiyapurayil','SP','Shahabas Puthiyapurayil','Inventory Assistant','Supports inventory accuracy through stock tracking, updates, and coordination.','shahabas.puthiyapurayil@synergypm.com','72',null,72,true),
('shahsad-sarfudheen','SS','Shahsad Sarfudheen','Operations Assistant','Supports core operations through accurate coordination, tracking, and execution.','shahsad.sarfudheen@synergypm.com','73',null,73,true),
('shamoonkhan-rajput','SR','Shamoonkhan Rajput','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','shamoonkhan.rajput@synergypm.com','74',null,74,true),
('simren-yehiya','SY','Simren Yehiya','Social Media Specialist','Plans social media strategy, content performance, and audience growth initiatives.','simren.yehiya@synergypm.com','75',null,75,true),
('siyad-ali','SA','Siyad Ali','Senior Graphic Designer','Leads creative design quality and visual direction across brand touchpoints.','siyad.ali@synergypm.com','76',null,76,true),
('sravan-panicker','SP','Sravan Panicker','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','sravan.panicker@synergypm.com','77',null,77,true),
('stany-santhoshkumar','SS','Stany Santhoshkumar','Customer Support','Supports customers with timely responses, issue resolution, and service quality.','stany.santhoshkumar@synergypm.com','78',null,78,true),
('subin-subair','SS','Subin Subair','Senior IT Operations Specialist','Leads IT operations reliability, system support, and infrastructure continuity.','subin.subair@synergypm.com','79',null,79,true),
('zune-yu-naing','ZY','Zune Yu Naing','Accountant','Manages financial records, reconciliations, and reporting with strong accuracy.','zune.yu.naing@synergypm.com','80',null,80,true)
on conflict (id) do update set
initials = excluded.initials,
name = excluded.name,
role = excluded.role,
bio = excluded.bio,
email = excluded.email,
number = excluded.number,
sort_order = excluded.sort_order,
is_active = excluded.is_active;
